apiVersion : apps/v1
kind: Deployment
metadata:
  name: karthicksaipipelinesjavascriptdocker 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: karthicksaipipelinesjavascriptdocker
  template:
    metadata:
      labels:
        app: karthicksaipipelinesjavascriptdocker 
    spec:
      containers:
        - name: karthicksaipipelinesjavascriptdocker 
          image: myprivateacrdemo.azurecr.io/karthicksaipipelinesjavascriptdocker
          ports:
          - containerPort: 8080